.\" Manpage for git-hotspot
.SH NAME
git hotspot \- List files within a repository which receive the most modifications.
.SH SYNOPSIS
git hotspot [-c|--count <number>]
.SH DESCRIPTION
List which files get modified the most
.SH OPTIONS
.TP
.I -c | --count <number>
Limit the output to <number> of files.
.SH AUTHOR
Joseph Woodward <joseph.woodward@xeuse.com>